spring.application.name=desi2026

spring.datasource.url=jdbc:mysql://localhost:3306/desi2026
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

server.port=8081